<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>sonia_monitor</name>
  <version>0.0.1</version>
  <description>A package responsible for monitoring nodes and traffic</description>
  <maintainer email="log.club.sonia@etsmtl.net">Sonia LOG Team</maintainer>
  <license>TODO: License declaration</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>rosbag2_transport</depend>
  <depend>rosbag2_storage</depend>
  <depend>sonia_common_ros2</depend>
  <depend>std_srvs</depend>
  <depend>std_msgs</depend>
  
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>