@startuml template
    class main{
        }
    class SystemMonitor{
    
        + SystemMonitor()
        + ~SystemMonitor()
        - proccessNodeStatusCallback(msg : sonia_common_ros::msg::NodeStatus) : void        

    }
@enduml