@startuml Class Diagram
title Class Diagram
    class main{
        }
    class SystemMonitor{
        - _sources : std::vector<std::string>
        - _map_nodes : std::unordered_map<std::string, MonitoredNode>
    
        + SystemMonitor()
        + ~SystemMonitor()
        - proccessNodeStatusCallback(msg : sonia_common_ros2::msg::NodeStatus) : void
        - publishSystemStatus() : void
        - initializeNode(node_name : std::string) : void
        - checkConsistency(node_name : std::string) : void       

    }
    struct MonitoredNode{
        check_consistency : bool
        recieved_stamp : rclcpp::Time
        last_published_stamp : rclcpp::Time
        node_status : sonia_common_ros2::msg::NodeStatus
    }
@enduml