@startuml template

participant SystemMonitor as sys

-> sys : processNodeStatusCallback(msg : sonia_common_ros::msg::NodeStatus)
sys -> sys : publishSystemStatus()
sys -> sys : initializeNode(node: std::string)

@enduml