/system_monitor:
  ros__parameters:
    node_list:
      - Mission_server
      - blackbox_provider
      - dvl_provider
      - depth_provider
      - imu_provider
      - cam_provider
      - rs485_provider
      - proc_control
      - proc_planner
      - proc_vision
      - bag_server