/system_monitor:
  ros__parameters:
    node_list:
      - Mission_server
      - depth_provider
      - imu_provider
      - rs485_provider
      - proc_planner
      - proc_vision
      - proc_control
      - Bag_recorder